export const GET_INSTRUCTORS = "GET_INSTRUCTORS";
export const ADD_INSTRUCTOR = "ADD_INSTRUCTOR";
export const UPDATE_INSTRUCTOR = "UPDATE_INSTRUCTOR";
export const DELETE_INSTRUCTOR = "DELETE_INSTRUCTOR";
export const INSTRUCTORS_LOADING = "INSTRUCTORS_LOADING";
